version: '3.8'

services:
  softbank.api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: softbankdb
      POSTGRES_USER: softbankuser
      POSTGRES_PASSWORD: softbankpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: